### ISSUE TITLE
Falta agregar la sección de State of the Art

### ISSUE THREAD

**Issue by mariosky** [xochilt/recometpaper#2]
Se debe tener la sección mas o menos de esta manera:
Recommender Systems
Hibrid Recommender Systems
Context Aware Recommender Systems
Context,
Context Aware
CARS
Ejemplos de Sistemas en detalle, algoritmos y sus ventajas.
CARS de restaurantes o Turísticos
Que elementos se han tomado como parte del contexto

Que problemas tienen este tipo de sisstemas

Propuesta:

**Comment by xochilt** [comment]
ok, ya lo estoy corrigiendo.

**Comment by xochilt** [comment]
Corregidos el estado del arte y la introduccion.  :)  Estoy integrandolo a la tesis.

**Comment by mariosky** [comment]
ok

On Wednesday, 16 March 2016, Xochilt Ramirez notifications@github.com
wrote:

> Corregidos el estado del arte y la introduccion. :) Estoy integrandolo a
> la tesis.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/xochilt/recometpaper/issues/2#issuecomment-197645800

## 

Dr. Mario García Valdez
Instituto Tecnológico de Tijuana
Móvil: +52 (664) 123-7806
